export const FOLDER_NAMES = [
  "Social Posts",
  "Articles",
  "Videos & Talks",
  "Code",
  "Docs & Reference",
  "Papers",
  "Websites & Apps",
  "Need for Review",
] as const;

export const CONTENT_FOLDER_NAMES = FOLDER_NAMES.filter(
  (name) => name !== "Need for Review",
);

export const SEED_TAGS = [
  "ai",
  "api",
  "architecture",
  "automation",
  "backend",
  "business",
  "career",
  "cloud",
  "code-quality",
  "data",
  "database",
  "design",
  "devops",
  "distributed-systems",
  "education",
  "frontend",
  "guide",
  "infrastructure",
  "javascript",
  "leadership",
  "machine-learning",
  "management",
  "mobile",
  "open-source",
  "performance",
  "product",
  "programming",
  "python",
  "reference",
  "research",
  "security",
  "software-engineering",
  "startup",
  "system-design",
  "testing",
  "tools",
  "typescript",
  "ux",
  "web",
  "writing",
] as const;

export const DOMAIN_FOLDER_MAP = {
  "x.com": "Social Posts",
  "twitter.com": "Social Posts",
  "reddit.com": "Social Posts",
  "news.ycombinator.com": "Social Posts",
  "linkedin.com": "Social Posts",
  "bsky.app": "Social Posts",
  "mastodon.social": "Social Posts",
  "medium.com": "Articles",
  "substack.com": "Articles",
  "youtube.com": "Videos & Talks",
  "youtu.be": "Videos & Talks",
  "vimeo.com": "Videos & Talks",
  "github.com": "Code",
  "gitlab.com": "Code",
  "npmjs.com": "Code",
  "pypi.org": "Code",
  "huggingface.co": "Code",
  "developer.mozilla.org": "Docs & Reference",
  "wikipedia.org": "Docs & Reference",
  "arxiv.org": "Papers",
  "acm.org": "Papers",
  "ieee.org": "Papers",
} as const;
