"use strict";
const browserApi=globalThis.browser??globalThis.chrome;
let connection=null,metadata={};
const byId=id=>document.getElementById(id);
async function request(path,options={}){const response=await fetch(connection.deployment+path,{...options,headers:{authorization:`Bearer ${connection.token}`,"content-type":"application/json",...(options.headers||{})}});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message||"Request failed");return body}
async function connect(){const deployment=new URL(byId("deploymentUrl").value).origin,token=byId("captureToken").value.trim();const granted=await browserApi.permissions.request({origins:[deployment+"/*"]});if(!granted)throw new Error("Deployment access was not granted");connection={deployment,token};await browserApi.storage.local.set({laterGatorConnection:connection});await load()}
async function pageMetadata(){const [tab]=await browserApi.tabs.query({active:true,currentWindow:true});if(!tab?.url)return{};const results=await browserApi.scripting.executeScript({target:{tabId:tab.id},func:()=>({description:document.querySelector('meta[name="description"]')?.content||document.querySelector('meta[property="og:description"]')?.content||"",image:document.querySelector('meta[property="og:image"]')?.content||document.querySelector('meta[name="twitter:image"]')?.content||""})});return{url:tab.url,title:tab.title||"",...(results[0]?.result||{})}}
async function load(){connection=(await browserApi.storage.local.get("laterGatorConnection")).laterGatorConnection||null;byId("connectionPanel").hidden=connection!==null;byId("captureForm").hidden=connection===null;if(!connection)return;metadata=await pageMetadata();byId("sourceUrl").value=metadata.url||"";byId("pageTitle").textContent=metadata.title||"Current page";byId("pageDescription").textContent=metadata.description||"";if(metadata.image){byId("preview").src=metadata.image;byId("preview").hidden=false}const options=await request("/api/capture/options",{method:"GET",headers:{}});byId("folder").innerHTML=options.folders.map(folder=>`<option value="${folder.id}" ${folder.slug==="unsorted"?"selected":""}>${folder.name}</option>`).join("");byId("tags").placeholder=options.tags.slice(0,4).map(tag=>tag.display_name).join(", ")||"Add tags…"}
byId("connectButton").addEventListener("click",()=>connect().catch(error=>byId("status").textContent=error.message));
byId("reconnectButton").addEventListener("click",()=>{byId("connectionPanel").hidden=false;byId("captureForm").hidden=true;byId("deploymentUrl").value=connection?.deployment||""});
byId("captureForm").addEventListener("submit",async event=>{event.preventDefault();const button=byId("saveButton");button.disabled=true;byId("status").textContent="Saving…";try{const body=await request("/api/capture/bookmarks",{method:"POST",body:JSON.stringify({requestId:crypto.randomUUID(),url:byId("sourceUrl").value,linkedUrl:byId("linkedUrl").value||null,title:metadata.title||null,description:metadata.description||null,note:byId("note").value||null,folderId:byId("folder").value,tags:byId("tags").value.split(",").map(value=>value.trim()).filter(Boolean),favorite:byId("favorite").checked,thumbnailUrl:metadata.image||null})});const labels={saved:"Saved",already_saved:"Already saved",saved_and_linked:"Saved and linked",source_saved_link_failed:"Source saved; link failed"};byId("status").textContent=labels[body.result]||"Saved"}catch(error){byId("status").textContent="Failed: "+error.message}finally{button.disabled=false}});
load().catch(error=>{byId("status").textContent=error.message;byId("connectionPanel").hidden=false;byId("captureForm").hidden=true});
