// Bundles the browser frontend into content-hashed files under web/assets and
// writes a manifest the Worker imports. The hash is the cache key, so there is
// no manual asset version to forget to bump.
import esbuild from "esbuild";
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const PUBLIC_DIR = "web/public";
const OUT_DIR = `${PUBLIC_DIR}/assets`;
const IMG_SRC = "web/img";
const MANIFEST = "src/v6/generated/asset-manifest.ts";

rmSync(PUBLIC_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });
mkdirSync("src/v6/generated", { recursive: true });

// web/public is rebuilt from scratch every run, so illustrations and setup
// screenshots live in a tracked source directory and are copied in. They are
// referenced by stable paths rather than content hashes because the setup
// guides link to them by name.
if (existsSync(IMG_SRC)) cpSync(IMG_SRC, `${PUBLIC_DIR}/img`, { recursive: true });

const temporaryDirectory = mkdtempSync(join(tmpdir(), "later-gator-web-"));
const compiledCss = join(temporaryDirectory, "app.css");
const tailwindExecutable = join(
  "node_modules",
  ".bin",
  process.platform === "win32" ? "tailwindcss.cmd" : "tailwindcss",
);

let result;
try {
  execFileSync(
    tailwindExecutable,
    ["--input", "web/src/app.css", "--output", compiledCss, "--minify"],
    { stdio: "inherit" },
  );
  result = await esbuild.build({
    entryPoints: ["web/src/main.ts", compiledCss],
    outdir: OUT_DIR,
    bundle: true,
    minify: true,
    sourcemap: false,
    format: "esm",
    target: ["es2022"],
    platform: "browser",
    entryNames: "[name].[hash]",
    metafile: true,
    logLevel: "warning",
  });
} finally {
  rmSync(temporaryDirectory, { recursive: true, force: true });
}

const entries = {};
for (const [outputPath, meta] of Object.entries(result.metafile.outputs)) {
  if (meta.entryPoint === undefined) continue;
  const publicPath = "/" + outputPath.replace(/^web\/public\//u, "");
  if (outputPath.endsWith(".css")) entries.css = publicPath;
  if (outputPath.endsWith(".js")) entries.js = publicPath;
}
if (entries.css === undefined || entries.js === undefined) {
  throw new Error("build-web: expected one hashed CSS entry and one hashed JS entry");
}

const manifestSource = `// Generated by scripts/build-web.mjs. Do not edit by hand.
export const ASSET_MANIFEST = {
  css: ${JSON.stringify(entries.css)},
  js: ${JSON.stringify(entries.js)},
} as const;
`;

// The manifest lives inside the watched src/ tree, so it must only be written
// when it actually changes. Touching it unconditionally makes `wrangler dev`
// rebuild in an endless loop.
if (!existsSync(MANIFEST) || readFileSync(MANIFEST, "utf8") !== manifestSource) {
  writeFileSync(MANIFEST, manifestSource);
}

writeFileSync(
  `${PUBLIC_DIR}/_headers`,
  `# Filenames are content-hashed, so a changed file is a changed URL.
/assets/*
  Cache-Control: public, max-age=31536000, immutable
  X-Content-Type-Options: nosniff
`,
);

console.log(`build-web: ${entries.css}, ${entries.js}`);
