/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.thumbnail-r2-types.jsonc --env-file=wrangler.types.vars --include-runtime=false --env-interface=R2ThumbnailBindingEnv worker-configuration-r2.d.ts` (hash: 98cb70b605618b606ef45d3d28c752bf)
interface __BaseEnv_R2ThumbnailBindingEnv {
	THUMBNAILS_R2: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_R2ThumbnailBindingEnv {}
}
interface R2ThumbnailBindingEnv extends __BaseEnv_R2ThumbnailBindingEnv {}
